project_name: "scope-kit"

languages:
- rust
- python

encoding: "utf-8"

ignore_all_files_in_gitignore: true

ignored_paths: []

read_only: false

excluded_tools: [
  "read_memory", "write_memory", "list_memories", "delete_memory", "onboarding", "check_onboarding_performed"
]

included_optional_tools: []

initial_prompt: ""
