project_name: "scope-kit"

languages:
- rust
- python

encoding: "utf-8"

ignore_all_files_in_gitignore: true

ignored_paths: []

read_only: false

excluded_tools: []

included_optional_tools: []

initial_prompt: ""
